<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
      

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/pizza-logo.png'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img style="width:30px; height: 30px;" src="<?php echo $this->basePath('img/pizza-logo.png') ?>" alt="Zend Framework 2"/></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="#dropdown">
                        <a  class="dropdown-toggle" data-toggle="dropdown" href="#" ><?php echo $this->translate('Pizza') ?> <span class="caret"></span> </a>

                         <ul class="dropdown-menu" role="menu">
				            <li><a href="<?php echo $this->url('pizza');?>">List of Pizzas</a></li>
				            <li><a href="<?php echo $this->url('pizza', array('action' => 'add'));?>">Add new pizza </a></li>
				           
				          </ul>


                        </li>

                        <li class="#dropdown">
                        <a  class="dropdown-toggle" data-toggle="dropdown" href="#" ><?php echo $this->translate('sandwich') ?> <span class="caret"></span> </a>

                         <ul class="dropdown-menu" role="menu">
				            <li><a href="<?php echo $this->url('sandwich');?>">List of sandwiches</a></li>
				            <li><a href="<?php echo $this->url('sandwich', array('action' => 'add'));?>">Add new sandwich </a></li>
				           
				          </ul>


                        </li>

                        <li class="#dropdown">
                        <a  class="dropdown-toggle" data-toggle="dropdown" href="#" ><?php echo $this->translate('Drink') ?> <span class="caret"></span> </a>

                         <ul class="dropdown-menu" role="menu">
				            <li><a href="<?php echo $this->url('drink');?>">List of drinks</a></li>
				            <li><a href="<?php echo $this->url('drink', array('action' => 'add'));?>">Add new drink </a></li>
				           
				          </ul>


                        </li>
                       
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by TheGentleTrainer with <b class="glyphicon glyphicon-heart"> </b>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
