<?php
echo $this->headTitle('Add new pizza');
?>

<div class="row">
  <div class="col-md-8"> <h1> Add new pizza </h1>
 </div>
  <div class="col-md-4">  </div>
</div>

<?php 

$form = $this->form;
$form->setAttribute('action', $this->url('pizza',array('action'=>'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('name')) . "</br>";
echo $this->formRow($form->get('ingredients')) . "</br>";
echo $this->formRow($form->get('smallprice')) . "</br>";
echo $this->formRow($form->get('bigprice')) . "</br>";
echo $this->formRow($form->get('familyprice')) . "</br>";
echo $this->formRow($form->get('partyprice')) . "</br>";
echo $this->formRow($form->get('addpizza')) . "</br>";
echo $this->form()->closeTag();

?>


