 <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
       
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img style="width : 100%;" src="<?php echo $this->basePath().'/img/pizza.jpg';?>">
          <div class="container">
            <div class="carousel-caption">
              <h1> Best of Pizza </h1>
              <p>We provide the Best Pizzas arround the world </p>
              <p><a class="btn btn-lg btn-primary" href="<?php echo $this->url('pizza');?>" role="button">Explore our collection</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img style="width : 100%;" src="<?php echo $this->basePath().'/img/sandwich.jpg';?>">
          <div class="container">
            <div class="carousel-caption">
              <h1>It's Sandwich time</h1>
             
              <p><a class="btn btn-lg btn-primary" href="<?php echo $this->url('sandwich');?>" role="button">Pick up your sandwich now ! </a></p>
            </div>
          </div>
        </div>
      
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->